---
- name: Include Acces parameter
  include_vars:
    file: "acces.yml"

- name: Generate and push base system configuration
  template:
    src: "base_system.j2"
    dest: "/tmp/{{ inventory_hostname }}_base.cfg"

- name: Generate and push spanning-tree configuration
  template:
    src: "spanning_tree.j2"
    dest: "/tmp/{{ inventory_hostname }}_spanning_tree.cfg"

- name: Generate and push VLAN configuration
  template:
    src: "vlans.j2"
    dest: "/tmp/{{ inventory_hostname }}_vlans.cfg"

- name: Generate and push L2 Uplink lag
  template:
    src: "port_lags_l2_uplink.j2"
    dest: "/tmp/{{ inventory_hostname }}_uplink.cfg"

- name: Generate and push access ports configuration
  template:
    src: "access_ports.j2"
    dest: "/tmp/{{ inventory_hostname }}_access_ports.cfg"

- name: Generate and push static ports configuration
  template:
    src: "static_ports.j2"
    dest: "/tmp/{{ inventory_hostname }}_static_ports.cfg"

- name: Generate and push security configuration
  template:
    src: "security.j2"
    dest: "/tmp/{{ inventory_hostname }}_security.cfg"

- name: Generate and push global NAC configuration
  template:
    src: "nac.j2"
    dest: "/tmp/{{ inventory_hostname }}_nac.cfg"
  #when: nac.enabled | default(false)

- name: Push all configurations to access switch
  arubanetworks.aoscx.aoscx_config:
    src: "/tmp/{{ inventory_hostname }}_{{ item }}.cfg"
  loop:
    - base
    - spanning_tree
    - vlans
    - uplink
    - access_ports
    - static_ports
    - nac
    - security
    