---
- name: Generate and push base system configuration
  template:
    src: "base_system.j2"
    dest: "/tmp/{{ hostname }}_base.cfg"

- name: Generate and push VLAN configuration
  template:
    src: "vlans.j2"
    dest: "/tmp/{{ inventory_hostname }}_vlans.cfg"

- name: Generate and push L2 Uplink PortChannel
  template:
    src: "portchannel_l2_uplink.j2"
    dest: "/tmp/{{ inventory_hostname }}_uplink.cfg"

- name: Generate and push access ports configuration
  template:
    src: "access_ports.j2"
    dest: "/tmp/{{ inventory_hostname }}_access_ports.cfg"

- name: Generate and push static ports configuration
  template:
    src: "static_ports.j2"
    dest: "/tmp/{{ inventory_hostname }}_static_ports.cfg"

- name: Generate and push security configuration
  template:
    src: "security.j2"
    dest: "/tmp/{{ inventory_hostname }}_security.cfg"

- name: Push all configurations to access switch
  arubanetworks.aoscx.aoscx_config:
    src: "/tmp/{{ inventory_hostname }}_{{ item }}.cfg"
  loop:
    - base
    - vlans
    - uplink
    - access_ports
    - static_ports
    - security