---
- name: Deploy Distribution Switch Configuration using Templates
  hosts: distribution
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  vars_files:
    - "{{ playbook_dir }}/inventory/production/group_vars/vault.yml"
  roles:
    - distribution_vsx
