---
- name: Deploy Access Switch Configuration
  hosts: access
  gather_facts: false
  collections:
    - arubanetworks.aos_switch

    #- "{{ playbook_dir }}/inventory/production/group_vars/vault.yml"
 vault_ansible_user: "admin"
 vault_ansible_password: "admin2023"
    
  roles:
    - access_switch