---
- name: Deploy Access Switch Configuration
  hosts: access
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
    
  vars_files:
    #- inventory/production/group_vars/password.yaml
    - "{{ playbook_dir }}/inventory/production/group_vars/password.yml"
    
  roles:
    - access_switch