---

# Standards réseau
dns_servers:
  - "192.168.1.254"
  - "8.8.8.8"

# Timeouts Ansible
ansible_command_timeout: 60
ansible_connection_timeout: 30

# Configuration système commune
system:
  timezone: "Europe/Paris"
  ntp_servers:
    - "192.168.1.254"
  domain_name: "entreprise.local"

# Configuration connexion
ansible_network_os: arubanetworks.aoscx.aoscx
#ansible_connection: ansible.netcommon.httpapi
#ansible_httpapi_use_ssl: yes
#ansible_httpapi_validate_certs: no
ansible_connection: network_cli
# vault_ansible_user et vault_ansible_password définis dans vault.yml
ansible_user: "{{ vault_ansible_user }}"                        
ansible_password: "{{ vault_ansible_password }}"