---
---
# Variables globales pour TOUS les équipements
vault_ansible_user: "admin"
# vault_ansible_password défini dans vault.yml

# Standards réseau
dns_servers:
  - "192.168.1.254"
  - "8.8.8.8"

# Timeouts Ansible
ansible_command_timeout: 60
ansible_connection_timeout: 30

# Configuration système commune
system:
  timezone: "Europe/Paris"
  ntp_servers:
    - "192.168.1.254"
  domain_name: "entreprise.local"