---

# Paramètres communs
role: "distribution"
mgmt_vlan: 10

mgmt_ip: "{{ ansible_host }}"  # Utilise l'IP de connexion
mgmt_subnet: "255.255.255.0"
gateway: "192.168.1.1"



# VLANs communs
common_vlans:
  - id: 100
    name: "USER"
  - id: 110
    name: "VOICE"
  - id: 200
    name: "SERVER"

# Configuration OSPF commune
ospf:
  process_id: 1
  area: "0.0.0.0"

# Standards de sécurité
security:
  spanning_tree_mode: "rstp"
  bpdu_guard: true