---
# Configuration commune WAN
role: "wan"
mgmt_vlan: 10

mgmt_ip: "{{ ansible_host }}"  # Utilise l'IP de connexion
mgmt_subnet: "255.255.255.0"
gateway: "192.168.1.1"


# BGP Configuration de base
bgp:
  as_number: 65001
  router_id: "{{ mgmt_ip }}"
  log_neighbor_changes: true

# Policies de routage
route_maps:
  - name: "TO_ISP"
    sequences:
      - sequence: 10
        action: "permit"

# Sécurité
security:
  ip_ssh: true
  ip_https: true
      