all:
  children:
    WAN:
      hosts:
        arubaCX-Rt1:
    
    DISTRIBUTION:
      hosts:
        arubaCX-SWD01:
        aruabaCX-SWD02:
      
      mlag_peers:
        hosts:
          arubaCX-SWD01:
          arubaCX-SWD02:
    ACCESS:
      hosts:
        arubaCX-SWA1:
        arubaCX-SWA2:
