all:
  children:
    WAN:
      arubaCX-Rt1:
    
    DISTRIBUTION:
      arubaCX-SWD01:
      aruabaCX-SWD02:
      
      mlag_peers:
        hosts:
          arubaCX-SWD01:
          arubaCX-SWD02:
    ACCESS:
      arubaCX-SWA1:
      arubaCX-SWA2:
