all:
  children:
    wan:
      hosts:
        arubaCX-Rt1:

    distribution:
      hosts:
        arubaCX-SWD01:
        arubaCX-SWD02:
      children:
        vsx:
          hosts:
            arubaCX-SWD01:
            arubaCX-SWD02:
            
    access:
      hosts:
        arubaCX-SWA01:
        arubaCX-SWA02:


