
- name: Generate and push base system configuration
  template:
    src: "base_system.j2"
    dest: "/tmp/{{ inventory_hostname }}_base.cfg"

- name: Generate and push RADIUS configuration
  template:
    src: "radius.j2"
    dest: "/tmp/{{ inventory_hostname }}_radius.cfg"

- name: Generate and push VSX configuration
  template:
    src: "vsx.j2"
    dest: "/tmp/{{ inventory_hostname }}_vsx.cfg"

- name: Generate and push VLAN configuration
  template:
    src: "vlans.j2"
    dest: "/tmp/{{ inventory_hostname }}_vlans.cfg"

- name: Generate and push prefix-lists configuration
  template:
    src: "prefix-lists.j2"
    dest: "/tmp/{{ inventory_hostname }}_prefix_lists.cfg"

- name: Generate and push ACLs configuration
  template:
    src: "acls.j2"
    dest: "/tmp/{{ inventory_hostname }}_acls.cfg"

- name: Generate and push route-maps configuration
  template:
    src: "route-maps.j2"
    dest: "/tmp/{{ inventory_hostname }}_route_maps.cfg"

- name: Generate and push BGP WAN LAG
  template:
    src: "port_lags_bgp_wan.j2"
    dest: "/tmp/{{ inventory_hostname }}_wan_lag.cfg"

- name: Generate and push L2 Access LAGs
  template:
    src: "port_lags_l2_access.j2"
    dest: "/tmp/{{ inventory_hostname }}_access_lag.cfg"

- name: Generate and push BGP configuration
  template:
    src: "bgp.j2"
    dest: "/tmp/{{ inventory_hostname }}_bgp.cfg"

- name: Generate and push OSPF configuration
  template:
    src: "ospf.j2"
    dest: "/tmp/{{ inventory_hostname }}_ospf.cfg"

- name: Push all configurations to distribution switch
  arubanetworks.aoscx.aoscx_config:
    lines: "{{ lookup('file', '/tmp/' + inventory_hostname + '_' + item + '.cfg') | split('\n') }}"
    save_when: always
  loop:
    - base
    - radius
    - vsx
    - vlans
    - prefix_lists
    - acls
    - route_maps
    - wan_lag
    - access_lag
    - bgp
    - ospf
  loop_control:
    label: "{{ item }}"