---
# hast vars arubaCX-SWA01 SWITCH ACCES
# Données UNIQUES à ce switch
hostname: "arubaCX-SWA01"
ansible_host: 192.168.116.138 
role: "access"

mgmt_vlan: 10
mgmt_ip: "192.168.116.138"
mgmt_subnet: "255.255.255.0"
gateway: "192.168.116.1"

# Port LAG vers Distribution (L2)
lags_Uplink:
  - id: 10
    description: "PORTCHANNEL_TO_VSX_DISTRIBUTION"
    type: "switched"
    protocol: "lacp"
    mode: "active"
    members:
      - interface: "1/1/2"
      - interface: "1/1/3"
    vlans:
      allowed: "10,100,110,200"
      native: 1



# VLANs (L2 seulement)
vlans:
  - id: 10
    name: "MGMT"
  - id: 100
    name: "USER_DATA"
  - id: 110
    name: "USER_VOICE"
  - id: 200
    name: "SERVER"

# Ports d'accès utilisateurs (L2)
access_ports:
  - range: 
      - "1/1/4"
      - "1/1/5"
    description: "USER_PORTS"
    type: "access"
    vlan: 100
    voice_vlan: 110
    bpdu_guard: true
    portfast: true
    storm_control: true

  - range: "1/1/6-1/1/7"
    description: "SERVER_PORTS"
    type: "access"
    vlan: 200
    bpdu_guard: true

# Configuration sécurité
spanning_tree:
  mode: "rstp"
  priority: 32768

port_security:
  storm_control: true
  bpdu_guard: true