---
# Configuration de base
hostname: arubaCX-SWD01
role: distribution
vsx_role: "secondary"
ansible_host: 192.168.1.11

# Configuration VSX
vsx:
  system_mac: "00:01:02:03:04:05"     # MÊME MAC
  isl:
    interface: "1/1/4-1/1/5"
    description: "VSX_ISL_To_SWD02"
  keepalive:
    interface: "1/1/6"
    ip: "192.168.255.2"
    peer_ip: "192.168.255.1"

#  Port LAGs  vers Routeur WAN (BGP)   et Identique sur le peer SWD02
lags:
  - id: 100
    description: "LAG_TO_WAN_ROUTER"
    type: "routed"
    ip_address: "10.10.0.1/30"  # IP virtuelle VSX
    protocol: "lacp"
    mode: "active"
    members:
      - interface: "1/1/1"
        description: "PO100_MEMBER_TO_WAN_ROUTER_arubaCX-Rt1"

# Port LAGs vers switches d'accès (OSPF)
  - id: 10
    description: "lag_TO_ACCESS_SWA01"
    type: "switched"
    protocol: "lacp"
    mode: "active"
    members:
      - interface: "1/1/2"
        description: "lag10_MEMBER_TO_SWA01"
    vlans:
      allowed: "10,100,200"
      native: 1

  - id: 20
    description: "lag_TO_ACCESS_SWA02"
    type: "switched"
    protocol: "lacp"
    mode: "active"
    members:
      - interface: "1/1/3
        description: "lag20_TO_MEMBER_TO_ACC_02"
    vlans:
      allowed: "10,100,200"
      native: 1


# VLANs (OSPF)
vlans:
  - id: 10
    name: "MGMT"
    ip_address: "192.168.10.10/24"
    opsf_area: "0.0.0.0"
  - id: 100
    name: "USER"
    ip_address: "10.10.100.1/24"
    opsf_area: "0.0.0.0"
  - id: 200
    name: "SERVER"
    ip_address: "10.10.200.1/24"
    opsf_area: "0.0.0.0"

# Prefix Lists pour le filtrage
prefix_lists:
  - name: "LOCAL_NETWORKS"
    sequences:
      - sequence: 10
        action: "permit"
        network: "10.10.0.0/16"
        le: "24"
      - sequence: 20
        action: "permit"
        network: "192.168.10.0/24"
      - sequence: 99
        action: "deny"
        network: "0.0.0.0/0"
        le: "32"

  - name: "BGP_TO_OSPF"
    sequences:
      - sequence: 10
        action: "permit"
        network: "10.10.0.0/30"
      - sequence: 99
        action: "deny"
        network: "0.0.0.0/0"
        le: "32"

  - name: "OSPF_TO_BGP"
    sequences:
      - sequence: 10
        action: "permit"
        network: "10.10.100.0/24"
      - sequence: 20
        action: "permit"
        network: "10.10.200.0/24"
      - sequence: 99
        action: "deny"
        network: "0.0.0.0/0"
        le: "32"

# Route Maps pour la redistribution
route_maps:
  - name: "OSPF_TO_BGP"
    sequences:
      - sequence: 10
        action: "permit"
        match: "ip address prefix-list OSPF_TO_BGP"
        set: "metric 100"

  - name: "BGP_TO_OSPF"
    sequences:
      - sequence: 10
        action: "permit"
        match: "ip address prefix-list BGP_TO_OSPF"
        set: "metric-type 1"

  - name: "TO_WAN_arubaCX-Rt1"
    sequences:
      - sequence: 10
        action: "permit"
        match: "ip address prefix-list LOCAL_NETWORKS"

# Configuration BGP vers WAN
bgp:
  as_number: 65000
  router_id: "192.168.10.10"  # Router ID virtuel VSX
  networks:
    - "10.10.0.0/30"
    - "192.168.10.0/24" 
  neighbors:
    - ip: "192.168.10.2"
      remote_as: 65001
      description: "WAN_ROUTER_arubaCX-Rt1"
      next_hop_self: true
      route_map_out: "TO_WAN_arubaCX-Rt1"
  redistribute:
    - protoccol: "ospf" 
      route_map: "OSPF_TO_BGP"   

# Configuration OSPF pour LAN
ospf:
  process_id: 1
  router_id: "192.168.10.10"
  passive_interfaces:
    - "vlan10"
    - "vlan100"
    - "vlan200"
  networks:
    - "192.168.10.0/24"
    - "10.10.100.0/24"
    - "10.10.200.0/30"
  redistribute:
    - protocol: bgp
      route_map: "BGP_TO_OSPF"
    - protocol: "connected"
      route_map: "BGP_TO_OSPF"


# ACLs pour le contrôle d'accès
acls:
  - name: "MGMT_ACCESS"
    type: "ip"
    sequences:
      - sequence: 10
        action: "permit"
        source: "192.168.10.0/24"
        destination: "any"
      - sequence: 20
        action: "deny"
        source: "any"
        destination: "any"

  - name: "BGP_PEERS"
    type: "ip"
    sequences:
      - sequence: 10
        action: "permit"
        source: "10.10.0.2/32"
        destination: "any"
      - sequence: 20
        action: "deny"
        source: "any"
        destination: "any"