---
role: distribution
mlag: arubaCX-SWD1
uplinks:
  1:
    interface_id: 1/1/1
    description: "WAN arubCX-Rt1"
peerlinks:
  1:
    interface_id: 1/1/4
    description: "DISTRIBUTION arubaCX-SWD2"
  2:
    interface_id: 1/1/5
    description: "DISTRIBUTION arubaCX-SWD2"
downlinks:
  1:
    interface_id: 1/1/2
    description: "Acces arubaCX-SWA1"
  2:
    interface_id: 1/1/3
    description: "Acces arubaCX-SWA2"  